name: Validate

on:
  - pull_request
  - push

permissions: {}

env:
  COREPACK_DEFAULT_TO_LATEST: 0

jobs:
  validate:
    name: Lint & Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    env:
      SKU_TELEMETRY: false
    steps:
      - name: Check out repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .nvmrc

      - name: Set up pnpm
        run: npm install --global corepack@0.31.0 && corepack enable pnpm && corepack install

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test:ci

      - name: Lint
        run: pnpm lint

      # sku lint does not dry run the build
      - name: Build fe
        run: pnpm fe build
