name: Validate

on:
  - pull_request
  - push

permissions: {}

env:
  COREPACK_DEFAULT_TO_LATEST: 0

jobs:
  validate:
    name: Lint & Test
    permissions:
      checks: write
    runs-on: ubuntu-latest
    env:
      SKU_TELEMETRY: false
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Set up pnpm
        run: npm install --global corepack@0.31.0 && corepack enable pnpm && corepack install

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test:ci

      - name: Lint
        run: pnpm lint

      # sku lint does not dry run the build
      - name: Build fe
        run: pnpm fe build
