name: Validate

on:
  - pull_request
  - push

jobs:
  validate:
    name: Lint & Test
    runs-on: ubuntu-latest
    env:
      CI: true
      SKU_TELEMETRY: false
    steps:
      - name: Check out repo
        uses: actions/checkout@master

      - name: Set up Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: yarn test

      - name: Lint
        run: yarn lint

      # sku lint does not dry run the build
      - name: Build fe
        run: yarn fe build
